### ISSUE TITLE
Run eval in IDE command

### ISSUE THREAD

**Issue by tacnoman** [derickr/dbgp#15]
Hello guys!
I'm creating an websocket to debug php codes with dbgp.
I'm following this documentation: https://xdebug.org/docs-dbgp.php#exec

I can run commands like step_in, step_over and another commands, but I want to run a php command (like an echo or implement a variable).

How can I run an echo command?

I tried theese commands:

> eval -i 1 -- echo $a;
> eval -i 1 -- base64(echo $a;)

There isn't any example in docs. How can I run an eval code in php and get the value returned?

Thanks for this.

**Comment by derickr** [comment]
First of all, you should try to avoid the eval command as much as you can, it's it *not* meant for reading and setting variable content, which is I think what you meant with "implement a variable".

That said, you need to actually base64 encode the string, not just put base64() around it. For example, your command would look like:

```eval -i 1 -- ZWNobyA7```

**Comment by tacnoman** [comment]
Hello @derickr 
I'm making a debugger for PHP and I have a question. I'm sorry to reopen this issue for this.

When I run this code in eval:

```php
preg_match('/a/', 'blabla', $result)
```

The variable $result does not exist before this code. If I try to get the variable $result with property_get I receive this error:

`300 - can not get property`

But if I run an eval with the content
```php
var_export($result, true)
```

I can see the variable.
```php
array (
  0 => 'a',
)
```
Why does this happen?

Thanks for this man.
I believe that the GitHub isn't the best place to ask things. There is another way to ask questions for you?

**Comment by derickr** [comment]
It's best to just email me (address is at the bottom of https://xdebug.org/support.php#email).

I would need more information to answer the question though - can you supply a full (small) script, and an accompanying remote log, as is described at https://xdebug.org/support.php#remote
