### ISSUE TITLE
Is there an DBGP dissector for Wireshark ?

### ISSUE THREAD

**Issue by vikyd** [derickr/dbgp#16]
Is there an DBGP dissector for Wireshark ?

For easier to understand Xdebug DBGP  communication.

**Comment by derickr** [comment]
No, there currently is no such dissector. The protocol isn't very hard though, so it shouldn't be too hard to *write* one. I found the instructions on https://www.wireshark.org/docs/wsdg_html_chunked/ChapterDissection.html very good though, when I updated the MongoDB dissector.

I would very much welcome one, and would be happy to bundle one with Xdebug if you end up writing one.

**Comment by derickr** [comment]
I'm closing this issue, as I have no plans myself to add this currently.
